language: ruby
sudo: false
cache: bundler
script: bundle exec ruby test.rb
---
language: ruby
cache: bundler
rvm:
  - 2.7.2
before_install: gem install bundler -v 2.1.4
install: bundle
script: bundle exec ruby test.rb
